# Virtual Quizzes is a monthly, charity fundraiser, Twitch-streamed quiz.  The charity changes each month - this link will take you to the current charity that we are fundraising for.

custom: ["https://www.virtual-quizzes.com/donate-here"]
